### ISSUE TITLE
Data retrieved, no devices created in Domoticz

### ISSUE THREAD

**Issue by E2V-Erik** [sdamasoc/domoticz_panasonic_CZ-TACG1#13]
Hi,

I installed this yesterday and I can see in the logging that the connection to panasonic cloud works. I get back to 4 devices we have in the cloud, see attached logging: [get_devices log.txt](https://github.com/sdamasoc/domoticz_panasonic_CZ-TACG1/files/13916888/get_devices.log.txt)

After this log, I only get this additional message in log: 
2024-01-12 10:08:39.219 Status: CW20_Airco: Initialized version 2.0.0, author 'sdamasoc'

I don't see any devices created in  Domoticz.

Also the setup button in the hardware TAB, for the plugin, is empty when clicked upon.
![image](https://github.com/sdamasoc/domoticz_panasonic_CZ-TACG1/assets/80317333/8a829b68-2dd6-4aa4-908e-7114cd3b5372)

![image](https://github.com/sdamasoc/domoticz_panasonic_CZ-TACG1/assets/80317333/52833d15-4f1a-420d-ad20-1e001eaa11f0)

**Comment by sdamasoc** [comment]
I saw yesterday that panasonic has published a new version of the application. At this moment it is still working for my device but maybe they have made some changes on the API.

Can you provide me more logs from domoticz?

**Comment by E2V-Erik** [comment]
Hi, is there a way to get that from CLI? The log in domoticz is very small, so the info I just saw is already wrapped

**Comment by sdamasoc** [comment]
I have Domoticz on an Ubuntu distribution, the log file is in _/tmp/domoticz.txt_

You can check your configuration, in _/etc/init.d/domoticz.sh_ you will find the path to the log in the daemon parameter _-log_

**Comment by E2V-Erik** [comment]
HI,

I found this message in the logging:
DEVICE TYPE 3IS NOT SUPPORTED YET

**Comment by E2V-Erik** [comment]
OK. I modified the phyton script line 103 checking for device type into this:
 elif(deviceType != "3"):

Now I have the devices created, 8 for each AC.
![image](https://github.com/sdamasoc/domoticz_panasonic_CZ-TACG1/assets/80317333/e166c8ed-c814-44f5-82cc-8f7e0a5d12b4)

I am only surprised about the TYPE for MODE, as that should be the one setting it to cool, heat, dry

Will further investigate.

Interested to understand why type 3 was excluded?

**Comment by E2V-Erik** [comment]
I am sorry. When looking in the Switch tab, I do see that Mode indeed has a dropdown to set it. Sorry. Should have checked.
![image](https://github.com/sdamasoc/domoticz_panasonic_CZ-TACG1/assets/80317333/3ba5bae8-8596-4b44-aab0-932e456563b6)

**Comment by sdamasoc** [comment]
I'm working on the full support of type 3 devices. 
You can give a try with the branch 2.0.0 which is quite stable now.
If everything works for you I can merge the changes on the master branch.

**Comment by paninoalsugo** [comment]
Hi all, I have same problem with device type 4, changing elif block code all seems to work correctly.

**Comment by sdamasoc** [comment]
I have a device type 1, once some had issues and he had a device type 2 so I decided to just support type 1 as I had no idea of the api for a type 2.
Now with the help of @Marcel81 I implemented the code for device type 2 and 3, it was on a branch but I just merged it on the master.

@paninoalsugo If you have a type 4 and the modified code works it should be solved with this new version

**Comment by paninoalsugo** [comment]
Yes, I can confirm, type 4 works well

**Comment by sdamasoc** [comment]
code merged, issue closed
