### ISSUE TITLE
Does not work without any other change after a couple of months

### ISSUE THREAD

**Issue by thron-1** [sdamasoc/domoticz_panasonic_CZ-TACG1#8]
After installing this plugin sometime around Q3/2022 all device, I have two configured in comfort cloud, are recognized and work as aspected. Mid of January this year the device are not useable any more and in the log are this error:

2023-03-22 08:42:10.007 Error: PanasonicCC: 'Heartbeat' failed 'JSONDecodeError':'Expecting value: line 1 column 1 (char 0)'.
2023-03-22 08:42:10.007 Error: PanasonicCC: Exception traceback:
2023-03-22 08:42:10.007 Error: PanasonicCC: ----> Line 262 in '/home/sysadmin/domoticz/plugins/domoticz_panasonic_CZ-TACG1/plugin.py'
2023-03-22 08:42:10.007 Error: PanasonicCC: ----> Line 71 in '/home/sysadmin/domoticz/plugins/domoticz_panasonic_CZ-TACG1/plugin.py'
2023-03-22 08:42:10.007 Error: PanasonicCC: ----> Line 340 in '/home/sysadmin/domoticz/plugins/domoticz_panasonic_CZ-TACG1/plugin.py'
2023-03-22 08:42:10.007 Error: PanasonicCC: ----> Line 319 in '/home/sysadmin/domoticz/plugins/domoticz_panasonic_CZ-TACG1/plugin.py'
2023-03-22 08:42:10.007 Error: PanasonicCC: ----> Line 357 in '/usr/lib/python3.8/json/__init__.py'
2023-03-22 08:42:10.007 Error: PanasonicCC: ----> Line 337 in '/usr/lib/python3.8/json/decoder.py'
2023-03-22 08:42:10.007 Error: PanasonicCC: ----> Line 355 in '/usr/lib/python3.8/json/decoder.py'

Restart Domotic, System and remove/reinstall the plugin does not fix the problem.

Any suggestions?

**Comment by sdamasoc** [comment]
It would be nice to enable DEBUG logs and send the JSON requests/responses so I will be able to analyse them.

But can you already check that you use the last version of confort cloud API:
[cid:f60239a7-f005-4439-8f72-eb8f4a8bfd75]
If you have re-pulled the plugin from github you should have the last version.

If you are confortable with python scripts there is also a script to test the API on the repository.

Sérgio

________________________________
From: thron-1 ***@***.***>
Sent: Wednesday, March 22, 2023 08:49
To: sdamasoc/domoticz_panasonic_CZ-TACG1 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [sdamasoc/domoticz_panasonic_CZ-TACG1] Does not work without any other change other a couple of months (Issue #8)


After installing this plugin sometime around Q3/2022 all device, I have to configured in comfort cloud, are recognized and work as aspected. Mid of January this year the device are not useable any more and in the log are this error:

2023-03-22 08:42:10.007 Error: PanasonicCC: 'Heartbeat' failed 'JSONDecodeError':'Expecting value: line 1 column 1 (char 0)'.
2023-03-22 08:42:10.007 Error: PanasonicCC: Exception traceback:
2023-03-22 08:42:10.007 Error: PanasonicCC: ----> Line 262 in '/home/sysadmin/domoticz/plugins/domoticz_panasonic_CZ-TACG1/plugin.py'
2023-03-22 08:42:10.007 Error: PanasonicCC: ----> Line 71 in '/home/sysadmin/domoticz/plugins/domoticz_panasonic_CZ-TACG1/plugin.py'
2023-03-22 08:42:10.007 Error: PanasonicCC: ----> Line 340 in '/home/sysadmin/domoticz/plugins/domoticz_panasonic_CZ-TACG1/plugin.py'
2023-03-22 08:42:10.007 Error: PanasonicCC: ----> Line 319 in '/home/sysadmin/domoticz/plugins/domoticz_panasonic_CZ-TACG1/plugin.py'
2023-03-22 08:42:10.007 Error: PanasonicCC: ----> Line 357 in '/usr/lib/python3.8/json/init.py'
2023-03-22 08:42:10.007 Error: PanasonicCC: ----> Line 337 in '/usr/lib/python3.8/json/decoder.py'
2023-03-22 08:42:10.007 Error: PanasonicCC: ----> Line 355 in '/usr/lib/python3.8/json/decoder.py'

Restart Domotic, System and remove/reinstall the plugin does not fix the problem.

Any suggestions?

**Comment by thron-1** [comment]
Hey Sérgio,

thx for the fast answer. Yes I removed the plugin from Domoticz and the plugin directory and pulled it again from github with API Version 1.17.0. 

In my younger days I was a professional Assembler, Cobol, and C programmer, but did not coded fore a very very long time ;-). But I already used your test script after the reinstall the the plugin and got this with pdb3 testPlugin.py:

>>
_> /home/sysadmin/domoticz/plugins/domoticz_panasonic_CZ-TACG1/testPlugin.py(1)<module>()
-> import requests
(Pdb)  n
> /home/sysadmin/domoticz/plugins/domoticz_panasonic_CZ-TACG1/testPlugin.py(2)<module>()
-> import json
(Pdb) n
> /home/sysadmin/domoticz/plugins/domoticz_panasonic_CZ-TACG1/testPlugin.py(3)<module>()
-> import time
(Pdb) n
> /home/sysadmin/domoticz/plugins/domoticz_panasonic_CZ-TACG1/testPlugin.py(4)<module>()
-> from datetime import date
(Pdb) n
> /home/sysadmin/domoticz/plugins/domoticz_panasonic_CZ-TACG1/testPlugin.py(7)<module>()
-> token = None
(Pdb) n
> /home/sysadmin/domoticz/plugins/domoticz_panasonic_CZ-TACG1/testPlugin.py(8)<module>()
-> Parameters = {"Mode3": "1.17.0", "Address": "https://accsmart.panasonic.com", "Username" : "my username", "Password":"my password"}
(Pdb) n
> /home/sysadmin/domoticz/plugins/domoticz_panasonic_CZ-TACG1/testPlugin.py(11)<module>()
-> class PanasonicCZTACG1Plugin:
(Pdb) n
> /home/sysadmin/domoticz/plugins/domoticz_panasonic_CZ-TACG1/testPlugin.py(40)<module>()
-> def getToken():
(Pdb) n
> /home/sysadmin/domoticz/plugins/domoticz_panasonic_CZ-TACG1/testPlugin.py(59)<module>()
-> def getDevices():
(Pdb) n
> /home/sysadmin/domoticz/plugins/domoticz_panasonic_CZ-TACG1/testPlugin.py(86)<module>()
-> def getDeviceById(deviceid):
(Pdb) n
> /home/sysadmin/domoticz/plugins/domoticz_panasonic_CZ-TACG1/testPlugin.py(109)<module>()
-> def updateDeviceId(deviceid, parameterName, parameterValue):
(Pdb) n
> /home/sysadmin/domoticz/plugins/domoticz_panasonic_CZ-TACG1/testPlugin.py(134)<module>()
-> def DumpHTTPResponseToLog(httpResp, level=0):
(Pdb) n
> /home/sysadmin/domoticz/plugins/domoticz_panasonic_CZ-TACG1/testPlugin.py(158)<module>()
-> p1 = PanasonicCZTACG1Plugin()
(Pdb) n
> /home/sysadmin/domoticz/plugins/domoticz_panasonic_CZ-TACG1/testPlugin.py(159)<module>()
-> p1.onStart()
(Pdb) n
onStart called
header= X-APP-TYPE : 0
header= X-APP-VERSION : 1.17.0
header= Accept : application/json; charset=UTF-8
header= Content-Type : application/json
header= X-User-Authorization : None
header= User-Agent : G-RAC
getDevices={"message":"Token expires","code":4100}
Token is expired, renew!
getToken={"result":0,"uToken":"XXXXXXXXXXXXXXXXXXXXX","country":"DE","extUsrId":"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX","clientId":"XXXXXXXXXXXXXXXXXXXXXXXXXXXX","language":0}
header= X-APP-TYPE : 0
header= X-APP-VERSION : 1.17.0
header= Accept : application/json; charset=UTF-8
header= Content-Type : application/json
header= X-User-Authorization : XXXXXXXXXXXXXXXXXXXXX
header= User-Agent : G-RAC
getDevices={"uiFlg":false,"groupCount":1,"groupList":[{"groupId":926126,"groupName":"My House","pairingList":[],"deviceList":[{"deviceGuid":"CS-Z35XKEW+4886936551","deviceType":"3","deviceName":"KlimaWZ","permission":3,"deviceModuleNumber":"CS-Z35XKEW","deviceHashGuid":"e2d65f7f3ba96eed8d29819d98f0a4e4007bd65c5a97a4b600e64505a72f858a","modelVersion":1,"summerHouse":0,"iAutoX":false,"nanoe":true,"nanoeStandAlone":true,"autoMode":true,"heatMode":true,"fanMode":false,"dryMode":true,"coolMode":true,"ecoNavi":false,"powerfulMode":true,"quietMode":true,"airSwingLR":true,"autoSwingUD":true,"ecoFunction":0,"temperatureUnit":0,"modeAvlList":{"autoMode":1,"fanMode":1},"coordinableFlg":false,"parameters":{"operate":1,"operationMode":3,"temperatureSet":21.5,"fanSpeed":0,"fanAutoMode":1,"airSwingLR":1,"airSwingUD":0,"ecoMode":0,"ecoNavi":0,"nanoe":2,"iAuto":0,"actualNanoe":2,"airDirection":0,"ecoFunctionData":0,"lastSettingMode":0}},{"deviceGuid":"CS-Z35VKEW+4962406476","deviceType":"3","deviceName":"KlimaSZ","permission":3,"deviceModuleNumber":"CS-Z35VKEW","deviceHashGuid":"618c81a314c9509b3ed4363bccba49bd55caf5a5917b0ff01d7a4c57587d0587","modelVersion":1,"summerHouse":0,"iAutoX":false,"nanoe":false,"nanoeStandAlone":false,"autoMode":true,"heatMode":true,"fanMode":false,"dryMode":true,"coolMode":true,"ecoNavi":false,"powerfulMode":true,"quietMode":true,"airSwingLR":true,"autoSwingUD":false,"ecoFunction":0,"temperatureUnit":0,"modeAvlList":{"autoMode":1,"fanMode":1},"coordinableFlg":false,"parameters":{"operate":0,"operationMode":3,"temperatureSet":22.0,"fanSpeed":5,"fanAutoMode":1,"airSwingLR":5,"airSwingUD":4,"ecoMode":0,"ecoNavi":0,"nanoe":1,"iAuto":0,"actualNanoe":1,"airDirection":0,"ecoFunctionData":0,"lastSettingMode":0}}]}]}
Device KlimaWZ found (DeviceID=CS-Z35XKEW+4886936551).
Device KlimaSZ found (DeviceID=CS-Z35VKEW+4962406476).
onStart end
--Return--
> /home/sysadmin/domoticz/plugins/domoticz_panasonic_CZ-TACG1/testPlugin.py(159)<module>()->None
-> p1.onStart()
(Pdb) n
--Return--
> <string>(1)<module>()->None
(Pdb) n
The program finished and will be restarted_
<<

Is this what your are need or can I do something else to get more in depth information of the communication.
The credentials are verified in the Panasonic App, so they are correct! But there is a problem with a required token I guess.

Best regards
Ingo

(edit: removed your personal token)

**Comment by sdamasoc** [comment]
The test here seems to work fine, your 2 devices were found:
- Device KlimaWZ found (DeviceID=CS-Z35XKEW+4886936551).
- Device KlimaSZ found (DeviceID=CS-Z35VKEW+4962406476).

Have you changed your password or is it correct in the domoticz configuration? 

Can you enable the debug logs on domoticz and send me again the domoticz logs?

Your first error seems to come from the line 319:
`res = json.loads(response.text)`
and it cannot parse the response but just before this response is shown in the logs (line 318):
`Domoticz.Log("getToken=" + response.text)`
I'm interested to see which response you get that cannot be parsed as JSON string.

**Comment by thron-1** [comment]
Ok, thats very interesting. I did not change the password since november last year. Did it in the Panasonic cloud and in Domoticz and the devices worked in Domoticz till 15th of january 🤷🏼‍♂️. I will make a password change tomorrow and will try it again with enabled  Domoticz debuging.

Thanks for your testing and your time. I will come back to you after the test….

Ingo

**Comment by thron-1** [comment]
﻿Sergio,

could not change the password on the Panasonic webpage this morning and send them a email regarding this.  This afternoon I got a answer and they mentioned that my account was locked because of many unsuccessfully attempts to login to it. After they enabled the account again the device worked in Domoticz like before January 15th. So I think the problem was the locked account and not a technical thing in Domoticz. 

Thanks for your instant support! Great job 👏.

Regards

**Comment by sdamasoc** [comment]
Your welcome, happy to read that the problem is solved. 

Maybe I should implement something to stop the plug-in when it’s not possible to get a valid token after x retries… 🤔

**Comment by thron-1** [comment]
Hey Sergio,

hope you are doing well. For your Information; since a few days a ney Panasonic Comfort Cloud APP Version is available and since then the access with your Domoticz Plugin does not work any more. I got the following error with the test script.

Token is expired, renew!
getToken={"message":"New version app has been published","code":4106}

Best Regards

Ingo

**Comment by sdamasoc** [comment]
Hello Ingo,
I’ve published the new api version yesterday on GitHub but you can just change the API version in Domoticz hardware settings. 

Sergio
